/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ModelView;

import BLL.Applicant;
import BLL.ApplicationDetails;
import BLL.Job;
import BLL.Perdoruesi;
import DAL.AppFormException;
import DAL.ApplicantRepository;
import DAL.ApplicationDetailsRepository;
import DAL.JobRepository;
import ModelGiu.ApplicantComboBoxModel;
import ModelGiu.ApplicationDetailsTableModel;
import ModelGiu.JobComboBoxModel;
import java.awt.Color;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class AddApplicationForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form AddApplicationForm
     */
    public AddApplicationForm() {
        initComponents();
        loadComboBox();
        
    }
    
    ApplicantRepository ar = new ApplicantRepository();
    ApplicantComboBoxModel acbm = new ApplicantComboBoxModel();
    ApplicationDetailsRepository adr = new ApplicationDetailsRepository();
    ApplicationDetailsTableModel adtm = new ApplicationDetailsTableModel();
    JobRepository jr = new JobRepository();
    JobComboBoxModel jcbm = new JobComboBoxModel();
     public void loadComboBox(){
        try{
            List <Job> list = jr.findAll();
            jcbm.add(list);
            jobCBM.setModel(jcbm);
            jobCBM.repaint();
            List <Applicant> listaa = ar.findAll();
            acbm.add(listaa);
            applicantCBM.setModel(acbm);
            applicantCBM.repaint();
      
            
          
        }catch(AppFormException ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }
     
     public void loadTable(){
    
     try{
            List<ApplicationDetails> lista = adr.findAll();
            //adtm.setPageSize(5);
            //Perdoruesi p = pr.loginByUsernameAndPassword(usernameField.getText(), new String(passwordField.getPassword()));
           // for(int i = 0 ; i < lista.size() ; i++){
             //   if(lista.get(i).getApplicantID() == )
            adtm.addList(lista);
            
            table.setModel(adtm);
            adtm.fireTableDataChanged();
            //}
        }catch(AppFormException ex){
            Logger.getLogger(EmployerForm.class.getName()).log(Level.SEVERE,null,ex);
        }
    }
     
     public void clear(){
     idField.setText("");
      //employerCBM.setSelectedIndex(-1);
       // employerCBM.repaint();
       jobCBM.setSelectedIndex(-1);
        jobCBM.repaint();
         applicantCBM.setSelectedIndex(-1);
        applicantCBM.repaint();
             
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        saveB = new javax.swing.JButton();
        cancelB = new javax.swing.JButton();
        idField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        applicantCBM = new javax.swing.JComboBox();
        mistake = new javax.swing.JLabel();
        jobCBM = new javax.swing.JComboBox();

        idField.setEnabled(false);
        idField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idFieldActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        jLabel1.setText("Make a new Applicaction");

        saveB.setText("Save");
        saveB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBActionPerformed(evt);
            }
        });

        cancelB.setText("Cancel");

        idField1.setEnabled(false);
        idField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idField1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Application ID:");

        applicantCBM.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        applicantCBM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applicantCBMActionPerformed(evt);
            }
        });
        applicantCBM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                applicantCBMKeyReleased(evt);
            }
        });

        jobCBM.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jobCBM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jobCBMActionPerformed(evt);
            }
        });
        jobCBM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jobCBMKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(mistake, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                        .addGap(715, 715, 715)))
                .addContainerGap())
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(idField1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103)
                .addComponent(applicantCBM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jobCBM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saveB)
                .addGap(158, 158, 158)
                .addComponent(cancelB)
                .addGap(302, 302, 302))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(applicantCBM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jobCBM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 307, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveB)
                    .addComponent(cancelB))
                .addGap(18, 18, 18)
                .addComponent(mistake, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idFieldActionPerformed

    private void idField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idField1ActionPerformed

    private void applicantCBMKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_applicantCBMKeyReleased
        mistake.setText(" ");         // TODO add your handling code here:
    }//GEN-LAST:event_applicantCBMKeyReleased

    private void applicantCBMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applicantCBMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_applicantCBMActionPerformed

    private void jobCBMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jobCBMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jobCBMActionPerformed

    private void jobCBMKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jobCBMKeyReleased
        mistake.setText(" ");        // TODO add your handling code here:
    }//GEN-LAST:event_jobCBMKeyReleased
    ApplicationDetailsForm adf = new ApplicationDetailsForm();
    
    private void saveBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBActionPerformed
        // TODO add your handling code here:
         try{
            if(jobCBM.getSelectedIndex() == 0 || applicantCBM.getSelectedIndex() == 0){
            mistake.setText("You should fill all of the above field");
            }else{
           
                ApplicationDetails ad = new ApplicationDetails();
               ad.setJobID((Job)jcbm.getSelectedItem());
                ad.setApplicantID((Applicant)acbm.getSelectedItem());
                 adr.create(ad);
                 adf.loadTable();
           
            }
            clear();
            loadTable();}
        catch(AppFormException af){
            JOptionPane.showMessageDialog(this , "This data Exists");
        }
        
    }//GEN-LAST:event_saveBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox applicantCBM;
    private javax.swing.JButton cancelB;
    private javax.swing.JTextField idField;
    private javax.swing.JTextField idField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox jobCBM;
    private javax.swing.JLabel mistake;
    private javax.swing.JPanel panel;
    private javax.swing.JButton saveB;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
