/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ModelView;

/**
 *
 * @author DELL
 */
public class UserForm extends javax.swing.JFrame {

    /**
     * Creates new form UserForm
     */
    public UserForm() {
        initComponents();
         setSize(1300 , 700); 
    }
    
    public UserForm(int userRoli) {
        initComponents();
        //Nese doni me bo max screen e shkruni kodin me poshte:
        //setExtendedState(JFrame.MAXIMIZED_BOTH);
        setLocationRelativeTo(null);
        if(userRoli ==2){
            EnewJobB.setVisible(false);
            ElocationListB.setVisible(false);
           
        }else if(userRoli ==3){
            AemployerListB.setVisible(false);
            AjobListB.setVisible(false);
            AnewApplicationB.setVisible(false);
           // AcategoryListB.setVisible(false);
            
           
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        desktopPane = new javax.swing.JDesktopPane();
        AemployerListB = new javax.swing.JButton();
        AjobListB = new javax.swing.JButton();
        AcompanyListB = new javax.swing.JButton();
        AcategoryListB = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        AnewApplicationB = new javax.swing.JButton();
        desktopPane2 = new javax.swing.JDesktopPane();
        EnewJobB = new javax.swing.JButton();
        ElocationListB = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AemployerListB.setText("Employer List");
        AemployerListB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AemployerListBActionPerformed(evt);
            }
        });

        AjobListB.setText("Jobs avaliable");
        AjobListB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AjobListBActionPerformed(evt);
            }
        });

        AcompanyListB.setText("Companies");
        AcompanyListB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcompanyListBActionPerformed(evt);
            }
        });

        AcategoryListB.setText("Categoryes");
        AcategoryListB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcategoryListBActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("User form");

        AnewApplicationB.setText("Add a new Application");
        AnewApplicationB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnewApplicationBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout desktopPane2Layout = new javax.swing.GroupLayout(desktopPane2);
        desktopPane2.setLayout(desktopPane2Layout);
        desktopPane2Layout.setHorizontalGroup(
            desktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 909, Short.MAX_VALUE)
        );
        desktopPane2Layout.setVerticalGroup(
            desktopPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );

        EnewJobB.setText("Add a new Job to the list");
        EnewJobB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnewJobBActionPerformed(evt);
            }
        });

        ElocationListB.setText("Location List");
        ElocationListB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ElocationListBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(desktopPaneLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(AcategoryListB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AcompanyListB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AemployerListB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ElocationListB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AjobListB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(desktopPaneLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AnewApplicationB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desktopPaneLayout.createSequentialGroup()
                                .addComponent(EnewJobB, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)))
                        .addGap(75, 75, 75))
                    .addGroup(desktopPaneLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(desktopPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(127, Short.MAX_VALUE))))
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(desktopPaneLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(AcategoryListB, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116)
                .addComponent(AjobListB, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(ElocationListB, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(AemployerListB, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                .addComponent(AcompanyListB, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
            .addGroup(desktopPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AnewApplicationB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EnewJobB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(desktopPane2)
                .addGap(17, 17, 17))
        );
        desktopPane.setLayer(AemployerListB, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(AjobListB, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(AcompanyListB, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(AcategoryListB, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(AnewApplicationB, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(desktopPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(EnewJobB, javax.swing.JLayeredPane.DEFAULT_LAYER);
        desktopPane.setLayer(ElocationListB, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktopPane))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AcategoryListBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcategoryListBActionPerformed
        // TODO add your handling code here:
        CategoryListForm clf = new CategoryListForm();
        desktopPane2.add(clf);
        clf.show();
    }//GEN-LAST:event_AcategoryListBActionPerformed

    private void AcompanyListBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcompanyListBActionPerformed
        // TODO add your handling code here:
        CompanyListForm cclf = new CompanyListForm();
        desktopPane2.add(cclf);
        cclf.show();
    }//GEN-LAST:event_AcompanyListBActionPerformed

    private void AemployerListBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AemployerListBActionPerformed
        // TODO add your handling code here:
        EmployerListForm elf = new EmployerListForm();
        desktopPane2.add(elf);
        elf.show();
    }//GEN-LAST:event_AemployerListBActionPerformed

    private void AjobListBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AjobListBActionPerformed
        // TODO add your handling code here:
        JobListForm jlf = new JobListForm();
        desktopPane2.add(jlf);
        jlf.show();
    }//GEN-LAST:event_AjobListBActionPerformed

    private void AnewApplicationBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnewApplicationBActionPerformed
        // TODO add your handling code here:
        
        AddApplicationForm apf = new AddApplicationForm();
        desktopPane2.add(apf);
        apf.show();
    }//GEN-LAST:event_AnewApplicationBActionPerformed

    private void EnewJobBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnewJobBActionPerformed
        // TODO add your handling code here:
        AddJobForm ajf = new AddJobForm();
        desktopPane2.add(ajf);
        ajf.show();
    }//GEN-LAST:event_EnewJobBActionPerformed

    private void ElocationListBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ElocationListBActionPerformed
        // TODO add your handling code here:
        LocationListForm llf = new LocationListForm();
        desktopPane2.add(llf);
        llf.show();
    }//GEN-LAST:event_ElocationListBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AcategoryListB;
    private javax.swing.JButton AcompanyListB;
    private javax.swing.JButton AemployerListB;
    private javax.swing.JButton AjobListB;
    private javax.swing.JButton AnewApplicationB;
    private javax.swing.JButton ElocationListB;
    private javax.swing.JButton EnewJobB;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JDesktopPane desktopPane2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
